export const API_ENDPOINTS = {
    FLIGHTS: {
        BASE: '/flights',
        BY_ID: (id: number) => `/flights/${id}`,
        BY_NUMBER: (flightNumber: string) => `/flights/number/${flightNumber}`,
        BY_STATUS: (status: string) => `/flights/status/${status}`,
        BY_AUTOMATA_STATE: (state: string) => `/flights/automata-state/${state}`,
        BY_AIRLINE: (airline: string) => `/flights/airline/${airline}`,
        DETECT: '/flights/detect',
        SIMULATE: '/flights/simulate',
        SIMULATE_ARRIVAL: (id: number) => `/flights/${id}/arrival`,
        SIMULATE_DEPARTURE: (id: number) => `/flights/${id}/departure`,
        UPDATE_STATUS: (id: number) => `/flights/${id}/status`,
        STATS_COUNT: '/flights/stats/count',
    },
    GATES: {
        BASE: '/gates',
        BY_ID: (id: number) => `/gates/${id}`,
        BY_NUMBER: (gateNumber: string) => `/gates/number/${gateNumber}`,
        BY_STATUS: (status: string) => `/gates/status/${status}`,
        BY_TYPE: (type: string) => `/gates/type/${type}`,
        BY_TERMINAL: (terminal: string) => `/gates/terminal/${terminal}`,
        AVAILABLE: '/gates/available',
        UPDATE_STATUS: (id: number) => `/gates/${id}/status`,
        OCCUPY: (id: number) => `/gates/${id}/occupy`,
        FREE: (id: number) => `/gates/${id}/free`,
        ACTIVATE: (id: number) => `/gates/${id}/activate`,
        DEACTIVATE: (id: number) => `/gates/${id}/deactivate`,
        STATS_COUNT: '/gates/stats/count',
    },
    ASSIGNMENTS: {
        BASE: '/assignments',
        BY_ID: (id: number) => `/assignments/${id}`,
        BY_FLIGHT: (flightId: number) => `/assignments/flight/${flightId}`,
        BY_GATE: (gateId: number) => `/assignments/gate/${gateId}`,
        ACTIVE_DETAILS: '/assignments/active/details',
        HISTORY_GATE: (gateNumber: string) => `/assignments/history/gate/${gateNumber}`,
        HISTORY_FLIGHT: (flightNumber: string) => `/assignments/history/flight/${flightNumber}`,
        ACTIVATE_LEDS: (id: number) => `/assignments/${id}/activate-leds`,
        DEACTIVATE_LEDS: (id: number) => `/assignments/${id}/deactivate-leds`,
        RECORD_ARRIVAL: (id: number) => `/assignments/${id}/record-arrival`,
        COMPLETE: (id: number) => `/assignments/${id}/complete`,
        STATS_ACTIVE_COUNT: '/assignments/stats/active-count',
    },
    MONITORING: {
        DASHBOARD: '/monitoring/dashboard',
        LED_STATUS: '/monitoring/led-status',
        SYSTEM_HEALTH: '/monitoring/system-health',
    },
    AUTH: {
        LOGIN: '/auth/login',
        VALIDATE: '/auth/validate',
    },
} as const;
